# Generated by Django 4.2.30 on 2026-08-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='available_units',
            field=models.IntegerField(default=0, help_text='Currently available units'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='total_units',
            field=models.IntegerField(default=0, help_text='Total number of this car model available'),
        ),
    ]
